"""
    Dashboard Deutschland API

    Auf https://www.dashboard-deutschland.de bietet das Statistische Bundesamt DESTATIS einen Überblick zu gesellschaftlich und wirtschaftlich relevanten Daten aus unterschiedlichen Themenbereichen. Diese werden durch Grafiken und Texte ergänzt und regelmäßig aktualisiert. Damit soll eine Möglichkeit geboten werden, aktuelle Kennzahlen und deren Entwicklung übersichtlich darzustellen.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.DashboardDeutschland.model.get_category import GetCategory
from deutschland.DashboardDeutschland.model.get_layout_tiles import GetLayoutTiles

from deutschland import DashboardDeutschland

globals()["GetCategory"] = GetCategory
globals()["GetLayoutTiles"] = GetLayoutTiles
from deutschland.DashboardDeutschland.model.get import Get


class TestGet(unittest.TestCase):
    """Get unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGet(self):
        """Test Get"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Get()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
