"""
    Dashboard Deutschland API

    Auf https://www.dashboard-deutschland.de bietet das Statistische Bundesamt DESTATIS einen Überblick zu gesellschaftlich und wirtschaftlich relevanten Daten aus unterschiedlichen Themenbereichen. Diese werden durch Grafiken und Texte ergänzt und regelmäßig aktualisiert. Damit soll eine Möglichkeit geboten werden, aktuelle Kennzahlen und deren Entwicklung übersichtlich darzustellen.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.DashboardDeutschland.api.geo_api import GeoApi  # noqa: E501

from deutschland import DashboardDeutschland


class TestGeoApi(unittest.TestCase):
    """GeoApi unit test stubs"""

    def setUp(self):
        self.api = GeoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geo(self):
        """Test case for geo

        Zugriff auf Geojson-Daten zu Deutschland und den Ländern  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
